/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

//import java.util.Locale;

import controlador.Controlador_FRM_VentanaPrincipal;//se importo de un´paquete que creamos.
import modelo.ArrayEstudiante;
import modelo.Estudiante;


/**
 *
 * @author Bryan Blanco
 */
public class FDM_ventanaPrincipal extends javax.swing.JFrame {
      
     Estudiante estudiante;
     ArrayEstudiante array;
     FRM_MantenimientoEstudiantes mantenimientoEstudiantes;
     Controlador_FRM_VentanaPrincipal controladorVentanaPrincipal;
    /**
     * Creates new form FDM_ventanaPrincipal
     */
    public FDM_ventanaPrincipal() {
   
        initComponents();
        
        array=new ArrayEstudiante();
        estudiante=new Estudiante();
        
        this.setLocation(100,200);
       
        mantenimientoEstudiantes = new FRM_MantenimientoEstudiantes(array,estudiante);
        controladorVentanaPrincipal=new Controlador_FRM_VentanaPrincipal(mantenimientoEstudiantes);
       // AgregarEvento();
    }
   public void AgregarEvento()
   {
      this.jm_Salir.addActionListener(controladorVentanaPrincipal); 
      this.jmi_Estudiantes.addActionListener(controladorVentanaPrincipal);
   }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        jm_Salir = new javax.swing.JMenuItem();
        Mantenimiento = new javax.swing.JMenu();
        jmi_Estudiantes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N

        Archivo.setText("Archivo");

        jm_Salir.setText("Salir");
        Archivo.add(jm_Salir);

        BarraMenu.add(Archivo);

        Mantenimiento.setText("Mantenimiento");

        jmi_Estudiantes.setText("Estudiantes");
        Mantenimiento.add(jmi_Estudiantes);

        BarraMenu.add(Mantenimiento);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDM_ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDM_ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDM_ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDM_ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDM_ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenu Mantenimiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jm_Salir;
    private javax.swing.JMenuItem jmi_Estudiantes;
    // End of variables declaration//GEN-END:variables
}
