/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorVentanaEstudiantes;
//import javax.swing.JTextField;
import modelo.ArrayEstudiante;
import modelo.Estudiante;

/**
 *
 * @author Bryan Blanco
 */
public class FRM_MantenimientoEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoEstudiantes
     */
    ArrayEstudiante array;
    Estudiante estudiante;
    ControladorVentanaEstudiantes control;
    public FRM_MantenimientoEstudiantes(ArrayEstudiante array,Estudiante estudiante) {
       initComponents();
       setVisible(false);
       this.array=array;
        this.estudiante=estudiante;
        control =new ControladorVentanaEstudiantes(this,estudiante,array);
        EventoPanelAbajo();
        PanelArriba();
      
        //this.panel1.agregarEventos(control);agrega los escuchas por paneles
        //this.panel2.agregarEventos(control);
        
    }
    public void EventoPanelAbajo()
    {
          this.btn_Agregar.addActionListener(control);
          this.btn_Buscar.addActionListener(control);
          this.btn_Eliminar.addActionListener(control);
          this.btn_Modificar.addActionListener(control);
          this.JB_Limpiar.addActionListener(control);
    }
    public void PanelArriba()
    {
        this.btn_Buscar.addActionListener(control);
    }

    public int getJT_Cedula() {
        return Integer.parseInt(this.JT_Cedula.getText());
    }

    public void setJT_Cedula(int cedula) {
        this.JT_Nombre.setText(""+cedula);
    }

    public String getJT_Direccion() {
        return JT_Direccion.getText();
    }

    public void setJT_Direccion(String direccion) {
        this.JT_Direccion.setText(direccion);
    }

    public String getJT_NombreCompleto() {
        return JT_Nombre.getText();
    }

    public void setJT_NombreCompleto(String nombre) {
        this.JT_Nombre.setText(nombre);
    }
    
 public void  Mostrar(Estudiante es)
 {
     JT_Cedula.setText(""+ es.getCedula());
     JT_Nombre.setText(es.getNombre());
     JT_Direccion.setText(es.getCorreo());
 }
 public void Limpiar()
 {
     JT_Nombre.setText("");
     JT_Cedula.setText("");
     JT_Direccion.setText("");
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jl_Cedula = new javax.swing.JLabel();
        JL_NombreCompleto = new javax.swing.JLabel();
        JL_Correo = new javax.swing.JLabel();
        JT_Cedula = new javax.swing.JTextField();
        JT_Nombre = new javax.swing.JTextField();
        JT_Direccion = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        JB_Limpiar = new javax.swing.JButton();
        JLbuscar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_Agregar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_Cedula.setText("Cedula:");

        JL_NombreCompleto.setText("Nombre Completo:");

        JL_Correo.setText("Correo:");

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btn_Buscar.setActionCommand("Consulta");

        JB_Limpiar.setText("Limpiar espacios");

        JLbuscar.setText("Buscar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_NombreCompleto)
                    .addComponent(jl_Cedula)
                    .addComponent(JL_Correo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JT_Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JT_Nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLbuscar))
                    .addComponent(JT_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB_Limpiar)
                .addGap(138, 138, 138))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JT_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_Cedula)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(btn_Buscar)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_NombreCompleto)
                            .addComponent(JT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_Correo)
                            .addComponent(JT_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(JLbuscar)))
                .addGap(18, 18, 18)
                .addComponent(JB_Limpiar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png"))); // NOI18N
        btn_Agregar.setActionCommand("agregar");

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btn_Eliminar.setActionCommand("eliminar");

        btn_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        btn_Modificar.setActionCommand("modificar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btn_Agregar)
                .addGap(42, 42, 42)
                .addComponent(btn_Eliminar)
                .addGap(48, 48, 48)
                .addComponent(btn_Modificar)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Agregar)
                    .addComponent(btn_Eliminar)
                    .addComponent(btn_Modificar))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Limpiar;
    private javax.swing.JLabel JL_Correo;
    private javax.swing.JLabel JL_NombreCompleto;
    private javax.swing.JLabel JLbuscar;
    private javax.swing.JTextField JT_Cedula;
    private javax.swing.JTextField JT_Direccion;
    private javax.swing.JTextField JT_Nombre;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jl_Cedula;
    // End of variables declaration//GEN-END:variables

    public String es_Correo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public class es {

        public es() {
        }
    }
}

