/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
/**
 *
 * @author Bryan Blanco
 */
public class Panel_InformacionBasica extends javax.swing.JPanel {

    /**
     * Creates new form Panel_InformacionBasica
     */
    public Panel_InformacionBasica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Cedula = new javax.swing.JLabel();
        JL_NombreCompleto = new javax.swing.JLabel();
        JL_Direccion = new javax.swing.JLabel();
        JT_NombreCompleto = new javax.swing.JTextField();
        JT_Cedula = new javax.swing.JTextField();
        JT_Direccion = new javax.swing.JTextField();
        BTN_ConsultaRapida = new javax.swing.JButton();

        jl_Cedula.setText("Cedula");

        JL_NombreCompleto.setText("Nombre Completo:");

        JL_Direccion.setText("Direccion");

        BTN_ConsultaRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        BTN_ConsultaRapida.setActionCommand("Consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_NombreCompleto)
                    .addComponent(jl_Cedula)
                    .addComponent(JL_Direccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JT_Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(JT_NombreCompleto)
                    .addComponent(JT_Direccion))
                .addGap(41, 41, 41)
                .addComponent(BTN_ConsultaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Cedula)
                    .addComponent(JT_NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_ConsultaRapida))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_NombreCompleto)
                    .addComponent(JT_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Direccion)
                    .addComponent(JT_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ConsultaRapida;
    private javax.swing.JLabel JL_Direccion;
    private javax.swing.JLabel JL_NombreCompleto;
    private javax.swing.JTextField JT_Cedula;
    private javax.swing.JTextField JT_Direccion;
    private javax.swing.JTextField JT_NombreCompleto;
    private javax.swing.JLabel jl_Cedula;
    // End of variables declaration//GEN-END:variables

   // void addActionListener(ControladorVentanaEstudiantes estudian) {
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
}
